### ISSUE TITLE
Error on CreateWork

### ISSUE THREAD

**Issue by YuitoYamamoto** [is09-souzou/AppSync-Resolver-Mapping-Lambda#30]
Hello!
作品投稿時のエラーです!
タグを入れないまま[CREATE]を押すとエラーメッセージとして
```
"ValidationException: One or more parameter values were invalid: An string set  may not be empty↵	status code: 400, request id: BI16160FUMD3C5LDDU9ODK3R4JVV4KQNSO5AEMVJF66Q9ASUAAJG"
```
が返ってきてます！
どうか！どうかお願いします！
Thanks in advance!

**Comment by Shuhei28** [comment]
Tagを必須項目にしてたような気が

**Comment by NozomiSugiyama** [comment]
Testしました。
「空」ってどれかわからないんで一応両方

<img width="1013" alt="screen shot 2018-07-19 at 13 46 10" src="https://user-images.githubusercontent.com/19605052/42922128-4b549dca-8b5a-11e8-9f98-059bc7c0ddfe.png">
<img width="1013" alt="screen shot 2018-07-19 at 13 46 21" src="https://user-images.githubusercontent.com/19605052/42922129-4ba165d8-8b5a-11e8-823d-5461ba932f7b.png">
